name: Release
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🚧　Install
        run: yarn
      - name: 📦　Build
        run: yarn build

      - name: 🔑　Generate Token
        uses: wow-actions/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token

      - uses: ./
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
          GIT_AUTHOR_NAME: wow-actions-bot
          GIT_AUTHOR_EMAIL: wow-actions-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: wow-actions-bot
          GIT_COMMITTER_EMAIL: wow-actions-bot@users.noreply.github.com
