name: Release
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🚧　Install
        run: yarn
      - name: 📦　Build
        run: yarn build

      - name: Generate token
        uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extends: '@wow-actions/semantic-release-config'
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ env.bot_token }}
          GIT_AUTHOR_NAME: wow-actions-bot
          GIT_AUTHOR_EMAIL: wow-actions-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: wow-actions-bot
          GIT_COMMITTER_EMAIL: wow-actions-bot@users.noreply.github.com

      # - name: 🔑　Generate Token
      #   uses: wow-actions/use-app-token@v1
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.PRIVATE_KEY }}
      #     env_name: bot_token

      # - uses: ./
      #   with:
      #     GITHUB_TOKEN: ${{ env.bot_token }}
      #     GIT_COMMITTER_NAME: wow-actions-bot
      #     GIT_COMMITTER_EMAIL: wow-actions-bot@users.noreply.github.com
